### ISSUE TITLE
implement an alternative installer that's less opinionated

### ISSUE THREAD

**Issue by djeremiah** [back-stack/showcase#3]
local-install.sh served its purpose for KubeCon. Now we need an installer that can target more flexible environments.

**Comment by ManuInNZ** [comment]
Not sure if I read that right but the Configuration build package is also very `linux_amd64`
https://github.com/back-stack/showcase/blob/ef13fc0ab0d77b3a5539f9b2ad48b57f9b094fb3/.github/workflows/release.yaml#L41

If I am not mistaken, this is to package the crossplane CLI, and it assumes it will run on linux_amd64.

**Comment by ManuInNZ** [comment]
> Not sure if I read that right but the Configuration build package is also very `linux_amd64`
> 
> https://github.com/back-stack/showcase/blob/ef13fc0ab0d77b3a5539f9b2ad48b57f9b094fb3/.github/workflows/release.yaml#L41
> 
> If I am not mistaken, this is to package the crossplane CLI, and it assumes it will run on linux_amd64.

that said I am very new to the configuration package in crossplane.

**Comment by kurktchiev** [comment]
The new installation methodology, along with a DevContainer, has been merged @ManuInNZ. Please give it a spin.

**Comment by ManuInNZ** [comment]
will do this weekend
