### ISSUE TITLE
New install questions

### ISSUE THREAD

**Issue by danielsollondon** [back-stack/showcase#55]
Hi,
I am following the steps to install on [KinD](https://backstack.dev/install/#installing-locally-into-kind).

I run: `porter credentials generate back-stack-cloud-creds \ 
  --reference ghcr.io/back-stack/showcase-bundle:latest`

Then I am asked for setting these values and have these questions:

**How would you like to set credential "aws-credentials"**
_Question: I only have access to Azure, if I leave this blank now I get an error running the install command, what should this be set to?_

**How would you like to set credential "kubeconfig"**
_Question - in the doc it mentions leaving the kubeconfig empty,  if I leave this blank now I get an error running the install command, what should this be set to?_

**How would you like to set credential "vault-token"**
_Question - what vault token is this, is there something I need to create first?_

Thanks!

**Comment by kurktchiev** [comment]
I admit the docs need to be more precise with your questions.

You technically do not need to pass in credentials if you do not want to. You would not be able to provision things in the cloud, but the stack will stand up outside of that. [https://backstack.dev/install/#porter-bundle-info-settings](url)

Yeah, this is something we need to improve a little bit. You can pass in nothing and, after creation, edit the credentials set to remove the kubeconfig section `porter credentials edit....`.

The vault token should be set to `specific value` to `root`. This is just the token used internally for Vault.

**Comment by danielsollondon** [comment]
Thanks for this, and apologies for the back and forth, I will contribute back to the docs.

The source of my questions is during the install is that when I ran:
**porter credentials generate back-stack-cloud-creds --reference ghcr.io/back-stack/showcase-bundle:latest**

I do not pass in anything for aws-credentials, kubeconfig, vault-token, then I ran:

**porter install back-stack --reference ghcr.io/back-stack/showcase-bundle:latest --credential-set back-stack-cloud-creds --param repository=https://github.com/xxx/xxx** --allow-docker-host-access

I see the below:
```
rpc error: code = Unknown desc = environment variable env is not defined
rpc error: code = Unknown desc = environment variable env is not defined
rpc error: code = Unknown desc = environment variable env is not defined
...
not load credentials: 3 errors occurred:
        * unable to resolve credential back-stack-cloud-creds.aws-credentials from env : rpc error: code = Unknown desc = environment variable env is not defined
        * unable to resolve credential back-stack-cloud-creds.kubeconfig from env : rpc error: code = Unknown desc = environment variable env is not defined
        * unable to resolve credential back-stack-cloud-creds.vault-token from env : rpc error: code = Unknown desc = environment variable env is not defined
        ...
```
I'll try again now with your info - thanks for helping out!

**Comment by kurktchiev** [comment]
yeah this is definetly a bit that we need to make the docs clearer on. So if you make a credential set that is created inside porter and stored, which is why I was saying you would want to post creation edit the credentials and remove the blocks for aws-credentials (or at least set them to `value: nocreds-for-you-today`), kubeconfig and vault.

So as an example my local credentials file looks like this:
``` yaml
schemaType: CredentialSet
 schemaVersion: 1.0.1
 namespace: default
 name: back-stack-cloud-creds
 credentials:
   - name: aws-credentials
      source:
        value: addlater
   - name: azure-credentials
      source:
        value: addlater
   - name: github-token
     source:
       value: addlater
   - name: vault-token
     source:
       value: root
```

**Comment by danielsollondon** [comment]
That worked - thank you @kurktchiev !
